name: endaft
description: Operations and utilities for the enDaft (Dart, AWS, Flutter, Terraform) solution templates.
version: 0.0.4
homepage: https://endaft.dev/
repository: https://github.com/endaft/endaft-cli
issue_tracker: https://github.com/endaft/endaft-cli/issues

environment:
  sdk: '>=3.1.2 <4.0.0'

executables:
  endaft:

dependencies:
  meta: ^1.11.0
  path: ^1.9.0
  args: ^2.4.2
  yaml: ^3.1.2
  http: ^1.1.2
  archive: ^3.4.9
  equatable: ^2.0.5
  collection: ^1.18.0
  json_schema: ^5.1.3
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
  json_serializable: ^6.7.1
