name: endaft
description: Operations and utilities for the enDaft (Dart, AWS, Flutter, Terraform) solution templates.
version: 1.0.8
homepage: https://endaft.dev/
repository: https://github.com/endaft/endaft-cli
issue_tracker: https://github.com/endaft/endaft-cli/issues

environment:
  sdk: ">=2.15.1 <3.0.0"

executables:
  endaft:

dependencies:
  meta: ^1.7.0
  path: ^1.8.1
  args: ^2.3.0
  tint: ^2.0.0
  yaml: ^3.1.0
  archive: ^3.1.9
  equatable: ^2.0.3
  collection: ^1.15.0
  json_schema2: ^2.0.1
  json_annotation: ^4.4.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
  json_serializable: ^6.1.4
