name: endaft
description: Operations and utilities for the enDaft (Dart, AWS, Flutter, Terraform) solution templates.
version: 0.0.3
homepage: https://endaft.dev/
repository: https://github.com/endaft/endaft-cli
issue_tracker: https://github.com/endaft/endaft-cli/issues

environment:
  sdk: ">=2.18.0 <3.0.0"

executables:
  endaft:

dependencies:
  meta: ^1.8.0
  path: ^1.8.2
  args: ^2.3.1
  yaml: ^3.1.1
  http: ^0.13.5
  archive: ^3.3.1
  equatable: ^2.0.5
  collection: ^1.16.0
  json_schema2: ^2.0.2+9
  json_annotation: ^4.6.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.5
  json_serializable: ^6.3.1
