name: dfat
description: Operations and utilities for the DFAT (Dart, Flutter, AWS, Terraform) solution templates.
version: 1.0.7
homepage: https://pub-dev.dicatania.me/dfat/
repository: https://github.com/GioCirque/pub-dev
issue_tracker: https://github.com/GioCirque/pub-dev/issues

environment:
  sdk: ">=2.15.1 <3.0.0"

executables:
  dfat:

dependencies:
  meta: ^1.7.0
  path: ^1.8.1
  args: ^2.3.0
  tint: ^2.0.0
  yaml: ^3.1.0
  archive: ^3.1.8
  equatable: ^2.0.3
  collection: ^1.15.0
  json_schema2: ^2.0.1
  json_annotation: ^4.4.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
  json_serializable: ^6.1.4
