name: endaft
description: Operations and utilities for the enDaft (Dart, AWS, Flutter, Terraform) solution templates.
version: 0.0.4
homepage: https://endaft.dev/
repository: https://github.com/endaft/endaft-cli
issue_tracker: https://github.com/endaft/endaft-cli/issues

environment:
  sdk: '>=3.1.2 <4.0.0'

executables:
  endaft:

dependencies:
  meta: ">=1.11.0 <2.0.0"
  path: ">=1.9.0 <2.0.0"
  args: ^2.4.2
  yaml: ^3.1.2
  http: ">=0.13.1 <2.0.0"
  archive: ">=3.4.9 <5.0.0"
  equatable: ">=2.0.5 <3.0.0"
  collection: ">=1.18.0 <2.0.0"
  json_schema: ^5.1.3
  json_annotation: ">=4.8.1 <5.0.0"

dev_dependencies:
  lints: ">=3.0.0 <6.0.0"
  test: ">=1.24.9 <2.0.0"
  json_serializable: ">=6.7.1 <7.0.0"
