name: deploy

on:
  push:
    tags:
      - "v*"

jobs:
  cli:
    name: 🤖 cli
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: 🚀 Publish cli
        uses: RatakondalaArun/pub.dev-cd@v1.0.0
        with:
          creditionals: ${{secrets.PUB_DEV_CREDENTIALS}}
